import test from 'node:test';
import assert from 'node:assert/strict';
import {initialiseEmployees,dueEmployee,executeEmployeeDecision,runEmployeeInitiative} from '../trading-worker/employee-agents.js';
import {message} from '../trading-worker/governance.js';
const now=Date.parse('2026-10-03T12:00:00Z');
function fixture(){return {agents:['scout','analyst','risk','operator','auditor','designer'].map(id=>({id,name:id,paused:false})),company:{tasks:[]},governance:{messages:[]},messages:[],real:{events:[{id:'e1',symbol:'TEST',preScore:{eligible:true,score:80},confirmed:false}],book:{cash:10000,positions:[],closed:[]}},operating:{remainingEur:9,paceEurPerDay:.3},paused:false};}
const decision=(tool,extra={})=>({goal:'Comprobar evidencia',decision:'Falta fecha primaria',tool,target:'none',eventId:'',evidenceIds:['discovery'],nextTask:'Contrastar fecha',wakeHours:4,...extra});
test('employees have separate memories, mailboxes and wake schedules',()=>{const s=fixture(),a=initialiseEmployees(s,now);executeEmployeeDecision(s,'scout',decision('handoff',{target:'analyst',eventId:'e1',evidenceIds:['e1']}),now);assert.equal(a.actors.scout.memory.length,1);assert.equal(a.actors.analyst.memory.length,0);assert.equal(a.actors.analyst.inbox[0].from,'scout');assert.equal(a.actors.scout.nextWake,now+4*3600e3);assert.equal(a.actors.analyst.nextWake,now);});
test('an employee can prioritize real evidence without altering funds or approving trades',()=>{const s=fixture(),book=JSON.stringify(s.real.book);executeEmployeeDecision(s,'scout',decision('prioritize_research',{eventId:'e1',evidenceIds:['e1']}),now);assert.equal(s.real.events[0].employeePriority.owner,'scout');assert.equal(JSON.stringify(s.real.book),book);assert.throws(()=>executeEmployeeDecision(s,'operator',decision('prioritize_research',{eventId:'e1'}),now));assert.throws(()=>executeEmployeeDecision(s,'analyst',decision('prioritize_analysis',{eventId:'e1'}),now));assert.throws(()=>executeEmployeeDecision(s,'scout',decision('propose_change',{evidenceIds:['invented']}),now));});
test('idle initiatives have a shared daily ceiling, pacing, and individual pauses',()=>{const s=fixture(),a=initialiseEmployees(s,now);assert.equal(dueEmployee(s,now).id,'scout');s.agents[0].paused=true;assert.equal(dueEmployee(s,now).id,'analyst');a.lastDispatch=now;assert.equal(dueEmployee(s,now+30*60e3),null);a.runsToday=6;assert.equal(dueEmployee(s,now+2*3600e3),null);s.operating.remainingEur=0;assert.equal(dueEmployee(s,now+864e5),null);});
test('one bounded paid initiative records its actual decision and cost',async()=>{const s=fixture();let calls=0,checkpoints=0;await runEmployeeInitiative(s,{call:async(id,instructions,payload,schema,options)=>{calls++;assert.equal(id,'scout');assert.ok(options.capEur<=.0025);assert.equal(options.light,true);assert.ok(payload.tools.includes('wait'));return {...decision('wait'),_costEur:.0004};},checkpoint:async()=>checkpoints++,log:()=>{}},now);assert.equal(calls,1);assert.equal(s.company.agency.actors.scout.costEur,.0004);assert.equal(s.company.agency.actors.scout.lastAction.tool,'wait');assert.equal(s.agents[0].status,'esperando');assert.equal(checkpoints,2);});
test('pipeline results become actionable mail for the receiving specialist',()=>{const s=fixture(),a=initialiseEmployees(s,now);a.actors.analyst.nextWake=now+864e5;message(s,'scout','analyst','TEST: evidencia contrastada disponible',now);assert.equal(a.actors.analyst.inbox.length,1);assert.equal(a.actors.analyst.inbox[0].status,'pendiente');assert.equal(a.actors.analyst.nextWake,now);});
