import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {defaults,newBook,buy,sell,monitor,assess,equity,eligible,allocation,day} from '../trading-worker/core.js';
import {cycle,status,locked,storeSecret,secret,validateConfig,llm,initialState,verifyResearch} from '../trading-worker/engine.js';
import worker from '../trading-worker/index.js';
import {onRequest} from '../functions/control/api/trading/[[path]].js';
import {accessForUser} from '../functions/_lib/auth.js';
export function memoryEnv(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0008_trading_lab.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('../migrations/0009_trading_operating_budget.sql',import.meta.url),'utf8'));const wrap=(sql,args=[])=>({bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}});return {TRADING_ENCRYPTION_SECRET:'test-encryption-secret-at-least-thirty-two-characters',CONTROL_DB:{prepare:wrap,async batch(ops){db.exec('BEGIN');try{const result=[];for(const op of ops)result.push(await op.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}},_db:db};}
const t=Date.now(),asset={symbol:'SMALL',name:'Small Company Common Stock',exchange:'NASDAQ',marketCap:400e6,price:10,contractVerified:true,sector:'Industry'};
const event={id:'event1',date:new Date(t+7*864e5).toISOString(),confirmed:true,source:'https://example.com/ir',summary:'Confirmed event'};
const plan={entryMin:9.8,entryMax:10.2,stop:9.4,target:12.2,expiresAt:t+14*864e5};
const quote={bid:10,ask:10.02,realtime:true,time:t,dollarVolume:5e6};
test('Orders respect daily count and idempotency; capital reconciles after a gap stop',()=>{const b=newBook(t);const first=buy(b,asset,event,plan,quote,defaults,t);assert.ok(first.ok);assert.ok(first.qty>0);assert.equal(b.orders.length,1);assert.equal(buy(b,asset,event,plan,quote,defaults,t).ok,false);const trades=monitor(b,{SMALL:{...quote,bid:8,ask:8.02,time:t+1000}},defaults,t+1000);assert.equal(trades.length,1);assert.equal(trades[0].reason,'stop');assert.ok(trades[0].exit<plan.stop);assert.equal(b.positions.length,0);assert.ok(Math.abs(equity(b)-(b.initial+trades[0].pnl))<1e-8);assert.equal(b.orders.length,2);});
test('Stale, future, delayed and crossed quotes cannot buy or close positions',()=>{for(const q of [{...quote,time:t-121000},{...quote,time:t+10000},{...quote,realtime:false},{...quote,bid:11}])assert.equal(assess(newBook(t),asset,event,plan,q,defaults,t).ok,false);const b=newBook(t);buy(b,asset,event,plan,quote,defaults,t);assert.equal(sell(b,b.positions[0],{...quote,realtime:false},defaults,t),null);});
test('Missing evidence, low liquidity, wide spread, ETF and invalid plan are rejected',()=>{assert.equal(assess(newBook(t),asset,{...event,confirmed:false},plan,quote,defaults,t).ok,false);assert.equal(assess(newBook(t),asset,event,plan,{...quote,dollarVolume:1},defaults,t).ok,false);assert.equal(assess(newBook(t),asset,event,plan,{...quote,ask:11},defaults,t).ok,false);assert.ok(eligible({...asset,name:'Small ETF'}));assert.equal(assess(newBook(t),asset,event,{...plan,stop:11},quote,defaults,t).ok,false);});
test('Entry limits stop new buys while exits remain available',()=>{const b=newBook(t);b.entriesToday=2;assert.equal(buy(b,asset,event,plan,quote,defaults,t).ok,false);b.entriesToday=0;buy(b,asset,event,plan,quote,defaults,t);b.entriesToday=2;assert.equal(monitor(b,{SMALL:{...quote,bid:13,ask:13.02}},defaults,t).length,1);});
test('Owner-only boundary and CSRF are enforced before accessing worker',async()=>{assert.ok(accessForUser({username:'CesarVapor'}).views.includes('trading'));for(const name of ['SuperSanti86','guest'])assert.ok(!accessForUser({username:name}).capabilities.includes('trading:manage'));for(const [session,method,expected] of [[null,'GET',401],[{user:{username:'SuperSanti86'}},'GET',403],[{user:{username:'CesarVapor'},csrfToken:'secret'},'POST',403]]){const r=await onRequest({request:new Request('https://x/control/api/trading/key',{method}),env:{},data:{session},params:{path:['key']}});assert.equal(r.status,expected);}});
test('Encrypted API credentials are never returned by status; removal works',async()=>{const env=memoryEnv();await storeSecret(env,'openai','sk-private-value-for-test');assert.equal(await secret(env,'openai'),'sk-private-value-for-test');const row=env._db.prepare('SELECT cipher FROM trading_secrets').get();assert.ok(!row.cipher.includes('sk-private'));const s=await status(env);assert.equal(s.connections.openai,true);assert.ok(!JSON.stringify(s).includes('sk-private'));await storeSecret(env,'openai','');assert.equal(await secret(env,'openai'),null);});
test('Demo has isolated persistent book, two entries at most, no paid API calls',async()=>{const env=memoryEnv();await locked(env,async s=>{s.mode='demo';s.demo.assets=Array.from({length:1800},(_,i)=>({...asset,symbol:'SIM'+String(i+1).padStart(4,'0'),name:'Test Fixture Common Stock',marketCap:100e6+(i%400)*1e6}));});await cycle(env,{manual:true});let s=await status(env);assert.equal(s.mode,'demo');assert.equal(s.book.entriesToday,2);assert.equal(s.book.positions.length,2);assert.equal(s.budget.calls,0);assert.ok(s.universe.eligible>1000);await cycle(env,{manual:true});s=await status(env);assert.equal(s.book.entriesToday,2);const oldCash=s.book.cash;await locked(env,async s=>{s.mode='real';s.automatic=false;});const real=await status(env);assert.equal(real.book.cash,10000);assert.equal(real.book.orders.length,0);await locked(env,async s=>{s.mode='demo';});assert.equal((await status(env)).book.cash,oldCash);});
test('Lease rejects concurrent mutations rather than overwriting a book',async()=>{const env=memoryEnv();let finish;const wait=new Promise(r=>finish=r);const pending=locked(env,async()=>{await wait;});await new Promise(r=>setTimeout(r,20));await assert.rejects(()=>locked(env,async()=>{}),/tarea en ejecución/);finish();await pending;assert.equal((await status(env)).busy,false);});
test('Pause prevents entries and risk limits cannot be silently loosened',async()=>{const env=memoryEnv();await locked(env,async s=>{s.paused=true;});await cycle(env,{manual:true});assert.equal((await status(env)).book.orders.length,0);assert.throws(()=>validateConfig({maxEntries:100},defaults));assert.throws(()=>validateConfig({dailyBudget:100},defaults));assert.throws(()=>validateConfig({minCap:500e6,primaryCap:500e6},defaults));});
test('Retired bridge rejects all external ingestion',async()=>{const env=memoryEnv();const r=await worker.fetch(new Request('https://internal/bridge'),env,{waitUntil(){}});assert.equal(r.status,410);});

test('Default office is a real-data empty EUR ledger, with the requested team',async()=>{const s=await status(memoryEnv());assert.equal(s.mode,'real');assert.equal(s.book.currency,'EUR');assert.equal(s.book.cash,10000);assert.equal(s.book.orders.length,0);assert.equal(s.book.positions.length,0);assert.equal(s.config.maxPositions,20);assert.deepEqual(s.agents.map(a=>a.name),['Santi','Pedro','María','Erea','Augusto','Cadaqui']);});
test('EUR lots use tiered budgets, whole shares, FX and fees, and reconcile after closure',()=>{const b=newBook(t,'EUR');assert.equal(assess(b,asset,event,plan,quote,defaults,t).ok,false);b.fx={rate:1.1,time:t};assert.equal(allocation(b),500);const r=buy(b,asset,event,plan,quote,defaults,t);assert.ok(r.ok);assert.ok((r.qty*r.price+defaults.commission)/1.1<=500);assert.ok((r.qty*r.price+defaults.commission)/1.1+r.price/1.1>500);b.fx={rate:1.2,time:t+1000};const trade=sell(b,b.positions[0],{...quote,bid:12,ask:12.02,time:t+1000},defaults,t+1000);assert.ok(Math.abs(equity(b)-(10000+trade.pnl))<1e-8);b.cash=15000;assert.equal(allocation(b),750);b.cash=20000;assert.equal(allocation(b),1000);b.cash=14999;assert.equal(allocation(b),500);});
test('Capital is reused after exits; twenty positions is a hard maximum',()=>{const b=newBook(t);for(let i=0;i<20;i++){const now=t+Math.floor(i/2)*864e5;const a={...asset,symbol:'A'+i};const ev={...event,id:'ev'+i,date:new Date(now+864e5).toISOString()};const pl={...plan,expiresAt:now+864e5};assert.ok(buy(b,a,ev,pl,{...quote,time:now},defaults,now).ok);}assert.equal(b.positions.length,20);const now=t+11*864e5;const ev={...event,id:'extra',date:new Date(now+864e5).toISOString()},pl={...plan,expiresAt:now+864e5};assert.ok(assess(b,{...asset,symbol:'EXTRA'},ev,pl,{...quote,time:now},defaults,now).reasons.includes('Límite de posiciones'));const p=b.positions[0];sell(b,p,{...quote,bid:12,ask:12.02,time:now},defaults,now);assert.ok(buy(b,{...asset,symbol:'EXTRA'},ev,pl,{...quote,time:now},defaults,now).ok);assert.equal(b.positions.length,20);});

test('Scout accepts only consulted primary sources and keeps probabilities labelled estimates',()=>{const event={date:new Date(t+864e5).toISOString()};const a={confirmed:true,eventDate:event.date,primaryDomain:'company.example',sources:[{url:'https://ir.company.example/news',claim:'The issuer announces upcoming financial results.'}],_retrieved:['https://ir.company.example/news'],summary:'A verified primary issuer announcement with the exact upcoming date and financial evidence. '.repeat(3),probabilityPositive:55,upsidePct:15,downsidePct:12,confidence:'baja',uncertainties:'No calibrated forecast',worthAnalyzing:true};const v=verifyResearch(a,event,t);assert.equal(v.confirmed,true);assert.equal(v.research.estimated,true);assert.equal(verifyResearch({...a,_retrieved:[]},event,t).confirmed,false);assert.equal(verifyResearch({...a,eventDate:new Date(t-1000).toISOString()},event,t).confirmed,false);assert.throws(()=>verifyResearch({...a,probabilityPositive:150},event,t));});
test('Luna routes lightweight roles, counts web tool costs and Sol stops after two daily requests',async()=>{const env=memoryEnv();await storeSecret(env,'openai','sk-test-not-a-live-key-123456');const s=initialState();s.real.book.fx={rate:1};const original=globalThis.fetch;const requests=[];globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://api.openai.com/v1/responses');const b=JSON.parse(opts.body);requests.push(b);return Response.json({status:'completed',usage:{input_tokens:1000,output_tokens:100},output:[...(b.tools?[{type:'web_search_call',action:{sources:[{url:'https://company.example/ir'}]}}]:[]),{type:'message',content:[{type:'output_text',text:'{"approve":true}',annotations:[]}]}]});};try{const schema={type:'object',properties:{approve:{type:'boolean'}},required:['approve'],additionalProperties:false};const r=await llm(env,s,'scout','research',{},schema,{web:true});assert.deepEqual(r._retrieved,['https://company.example/ir']);assert.equal(requests[0].model,'gpt-6-luna');assert.equal(requests[0].max_tool_calls,2);assert.equal(requests[0].reasoning.effort,'none');const cost=env._db.prepare('SELECT spent FROM trading_budget').get();assert.ok(Math.abs(cost.spent-.01015)<1e-8);await llm(env,s,'risk','review',{},schema);assert.equal(requests[1].model,'gpt-6-luna');assert.equal(requests[1].max_output_tokens,500);await llm(env,s,'analyst','analyse',{},schema);await llm(env,s,'analyst','analyse',{},schema);await assert.rejects(()=>llm(env,s,'analyst','analyse',{},schema),/Dos análisis/);assert.equal(requests.length,4);}finally{globalThis.fetch=original;}});

test('Monthly operating rent blocks paid calls at exhaustion and preserves paper capital',async()=>{const env=memoryEnv();await storeSecret(env,'openai','sk-test-not-a-live-key-123456');const s=initialState();s.real.book.fx={rate:1};const month=day().slice(0,7);env._db.prepare('INSERT INTO trading_operating_budget(month,spent_eur,updated_at) VALUES (?,?,?)').run(month,10,Date.now());const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('Must not spend');};try{await assert.rejects(()=>llm(env,s,'scout','research',{},{}),/mensual/);assert.equal(calls,0);assert.equal(s.real.book.cash,10000);assert.equal(env._db.prepare('SELECT spent FROM trading_budget').get().spent,0);}finally{globalThis.fetch=original;}});
