CREATE TABLE IF NOT EXISTS trading_state (id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL, lease_token TEXT, lock_until INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trading_secrets (name TEXT PRIMARY KEY, cipher TEXT NOT NULL, iv TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trading_budget (day TEXT PRIMARY KEY, spent REAL NOT NULL DEFAULT 0, calls INTEGER NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS trading_calls (id TEXT PRIMARY KEY, day TEXT NOT NULL, model TEXT NOT NULL, reserved REAL NOT NULL, actual REAL, status TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trading_bridge (id INTEGER PRIMARY KEY CHECK(id=1),payload TEXT NOT NULL,updated_at INTEGER NOT NULL);
