const loginForm=document.getElementById('login-form');
const changeForm=document.getElementById('change-form');
const loginFeedback=document.getElementById('login-feedback');
const changeFeedback=document.getElementById('change-feedback');
let csrfToken='';
function setBusy(form,busy){form.querySelector('button').disabled=busy}
function showChange(){loginForm.hidden=true;changeForm.hidden=false;changeForm.elements.password.focus()}
async function checkExistingSession(){try{const response=await fetch('/control/api/session',{headers:{accept:'application/json'},credentials:'same-origin'});if(!response.ok)return;const data=await response.json();csrfToken=data.csrfToken||'';if(data.user?.mustChangePassword)showChange();else location.replace('/control/')}catch{}}
loginForm.addEventListener('submit',async(event)=>{event.preventDefault();loginFeedback.textContent='';setBusy(loginForm,true);const payload={username:loginForm.elements.username.value.trim(),password:loginForm.elements.password.value};try{const response=await fetch('/control/api/auth/login',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'login_failed');csrfToken=data.csrfToken;loginForm.elements.password.value='';if(data.user.mustChangePassword)showChange();else location.replace('/control/')}catch{loginFeedback.textContent='USERNAME OR PASSWORD NOT RECOGNISED'}finally{setBusy(loginForm,false)}});
changeForm.addEventListener('submit',async(event)=>{event.preventDefault();changeFeedback.className='feedback';changeFeedback.textContent='';const password=changeForm.elements.password.value;if(password!==changeForm.elements.confirmation.value){changeFeedback.textContent='PASSWORDS DO NOT MATCH';return}setBusy(changeForm,true);try{const response=await fetch('/control/api/auth/change-password',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json',accept:'application/json','x-csrf-token':csrfToken},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.error||'change_failed');changeFeedback.className='feedback success';changeFeedback.textContent='PASSWORD SECURED · OPENING MISSION CONTROL';setTimeout(()=>location.replace('/control/'),650)}catch(error){changeFeedback.textContent=error.message==='weak_password'?'USE 14+ CHARACTERS WITHOUT YOUR USERNAME':'PASSWORD COULD NOT BE UPDATED'}finally{setBusy(changeForm,false)}});
checkExistingSession();
