import {prepareDevelopment} from './development.js';
import {developmentFiles} from './office-boundary.js';
import {equity} from './core.js';
import {message} from './governance.js';
export const madridDay=t=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));
export const staff=['scout','analyst','risk','operator','designer','auditor'];
const obj=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const str={type:'string'},num={type:'number'},strings={type:'array',items:str};
const owner={type:'string',enum:staff};
export const voiceSchema=obj({facts:str,evidence:strings,idea:str,replyTo:str,uncertainty:str,nextTask:str});
export const chairSchema=obj({summary:str,decisions:{type:'array',maxItems:4,items:obj({title:str,reason:str,owner,kind:{type:'string',enum:['hold','experiment','workflow','visual']},evidence:strings,successMetric:str,reviewDays:num})},assignments:{type:'array',maxItems:6,items:obj({owner,task:str})},reportToCesar:str,codeFiles:{type:'array',maxItems:2,items:{type:'string',enum:developmentFiles}},codeRationale:str});
export const features=['revenueYoY','netMargin','fcf','debtToEbitda','shareGrowth','pe','pb','roe','return5d','return21d','return63d','relativeVolume','beta1y','averageDollarVolume','marketCap','signalStrength','daysToEvent'];
const ruleSchema=obj({feature:{type:'string',enum:features},op:{type:'string',enum:['gt','lt']},value:num,points:num});
export const programSchema=obj({scope:{type:'string',enum:['agent-office']},rationale:str,threshold:num,rules:{type:'array',maxItems:12,items:ruleSchema},workflow:obj({researchDailyLimit:num,researchIntervalMinutes:num,riskPct:num,minRR:num}),visual:obj({focus:{type:'string',enum:['risk','economics','pipeline']},theme:{type:'string',enum:['amber','violet','mint']},headline:str,panels:{type:'array',items:{type:'string',enum:['efficiency','radar','rules','communications','meetings','report']}},lighting:{type:'string',enum:['day','warm','night']}})});
export function initialiseCompany(s,now=Date.now()){s.company??={meetings:[],reports:[],versions:[],tasks:[],memory:{},activeProgram:null,shadowProgram:null,version:0};s.company.memory??={};return s.company;}
export function dueMeeting(s,now=Date.now()){
 const c=initialiseCompany(s,now),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(now)).split(':').map(Number),minutes=parts[0]*60+parts[1],day=madridDay(now);
 for(const [slot,start] of [['planning',660],['closing',1350]]){if(minutes<start)continue;const id=day+':'+slot,m=c.meetings.find(m=>m.id===id);if(!m)return {id,day,slot,scheduledTime:slot==='planning'?'11:00':'22:30'};if(['completa','omitida'].includes(m.status))continue;if(m.attempts<2&&(!m.retryAt||now>=m.retryAt))return m;}
 return null;
}
export function validateProgram(p){
 if(!p||p.scope!=='agent-office'||typeof p.rationale!=='string'||p.rationale.length>1500||!Number.isFinite(p.threshold)||p.threshold<30||p.threshold>90)throw Error('Programa fuera del ámbito o umbral inválido');
 if(!Array.isArray(p.rules)||p.rules.length>12)throw Error('Demasiadas reglas');for(const r of p.rules)if(!features.includes(r.feature)||!['gt','lt'].includes(r.op)||!Number.isFinite(r.value)||Math.abs(r.value)>1e12||!Number.isFinite(r.points)||Math.abs(r.points)>20)throw Error('Regla no válida');
 const w=p.workflow;if(!w||!Number.isInteger(w.researchDailyLimit)||w.researchDailyLimit<1||w.researchDailyLimit>12||!Number.isInteger(w.researchIntervalMinutes)||w.researchIntervalMinutes<30||w.researchIntervalMinutes>240||!Number.isFinite(w.riskPct)||w.riskPct<.1||w.riskPct>1||!Number.isFinite(w.minRR)||w.minRR<2||w.minRR>8)throw Error('Flujo fuera de los límites del laboratorio');
 const v=p.visual;if(!v||!['risk','economics','pipeline'].includes(v.focus)||!['amber','violet','mint'].includes(v.theme)||!['day','warm','night'].includes(v.lighting)||typeof v.headline!=='string'||v.headline.length>200||!Array.isArray(v.panels)||v.panels.length<2||new Set(v.panels).size!==v.panels.length||v.panels.some(x=>!['efficiency','radar','rules','communications','meetings','report'].includes(x)))throw Error('Diseño de oficina inválido');return p;
}
export function executeProgram(p,values,baseScore){validateProgram(p);let score=baseScore;for(const r of p.rules){const v=values[r.feature];if(Number.isFinite(v)&&(r.op==='gt'?v>r.value:v<r.value))score+=r.points;}return {score:Math.max(0,Math.min(100,Math.round(score))),threshold:p.threshold};}
export function testProgram(p){validateProgram(p);const empty=executeProgram(p,{},0),strong=executeProgram(p,{revenueYoY:.2,fcf:1e6,relativeVolume:2,marketCap:300e6},60);if(![empty.score,strong.score].every(Number.isFinite))throw Error('Prueba de programa fallida');return ['ámbito de oficina','métricas ausentes','puntuación finita','presupuesto inmutable','límites de riesgo','sin ejecución arbitraria'];}
export function installProgram(s,p,meeting,now=Date.now()){
 validateProgram(p);const c=initialiseCompany(s,now),tests=testProgram(p),previous={policy:{...s.policy},config:{riskPct:s.config.riskPct,minRR:s.config.minRR},ui:c.ui||null};
 // Operational and visual changes can run immediately. Strategy is an experiment first.
 const operational={researchDailyLimit:p.workflow.researchDailyLimit,researchIntervalMinutes:p.workflow.researchIntervalMinutes};
 Object.assign(s.policy,operational);s.policy.version++;c.ui=p.visual;
 const version={id:crypto.randomUUID(),version:++c.version,time:now,meetingId:meeting.id,program:p,source:'// Programa autónomo de Agent Office. Interpretado por el motor validado.\nexport default '+JSON.stringify(p,null,2)+';\n',previous,baseline:{closed:s.real.book.closed.length,equity:equity(s.real.book),drawdown:s.real.book.maxDrawdown||0},tests,status:'observación',notBefore:now+7*864e5,observations:0,lastObservationAt:0};
 if(c.shadowProgram){version.status='solo flujo y visual';version.gate='Hay un experimento previo en observación; no se reinicia por otra reunión';}else c.shadowProgram=version.id;c.versions.unshift(version);c.versions=c.versions.filter((v,i)=>i<20||v.id===c.shadowProgram||v.id===c.activeProgram);return version;
}
export function observeProgram(s,now=Date.now()){
 const c=initialiseCompany(s,now),active=c.versions.find(v=>v.id===c.activeProgram);
 if(active&&s.real.book.closed.length-active.baseline.closed>=10&&equity(s.real.book)-active.baseline.equity<-s.real.book.initial*.02){active.status='revertido';active.rollbackAt=now;c.activeProgram=null;s.config.riskPct=active.previous.config.riskPct;s.config.minRR=active.previous.config.minRR;message(s,'auditor','boss','Reversión automática de programa v'+active.version+': deterioro tras diez cierres; no demuestra causalidad',now);}
 const v=c.versions.find(v=>v.id===c.shadowProgram);if(!v||v.status!=='observación')return;
 if(now<v.notBefore||s.real.book.closed.length-v.baseline.closed<20||v.observations<100){v.gate='Esperar siete días, veinte cierres nuevos y cien observaciones contrastadas';return;}
 // Economic activation requires observed recovery, not merely elapsed time or a few wins.
 if(equity(s.real.book)<v.baseline.equity||s.real.book.maxDrawdown>v.baseline.drawdown+1){v.gate='Resultados insuficientes; continúa en observación';return;}
 c.activeProgram=v.id;c.shadowProgram=null;v.status='activo';v.activatedAt=now;s.policy.minScore=v.program.threshold;s.config.riskPct=v.program.workflow.riskPct;s.config.minRR=v.program.workflow.minRR;message(s,'auditor','boss','Programa de estrategia v'+v.version+' activado tras superar observación y validaciones',now);
}
export function augmentScore(s,event,asset,profile,rank,now=Date.now()){
 const c=initialiseCompany(s,now),values={...profile?.fundamentals?.metrics,...profile?.market,marketCap:asset.marketCap,signalStrength:event.signal?.strength||0,daysToEvent:event.date?(Date.parse(event.date)-now)/864e5:null};
 const shadow=c.versions.find(v=>v.id===c.shadowProgram);if(shadow){const scored=executeProgram(shadow.program,values,rank.score);event.experiment={version:shadow.version,...scored,eligible:!rank.blocked&&scored.score>=scored.threshold,observationOnly:true};if(now-shadow.lastObservationAt>3600e3){shadow.observations++;shadow.lastObservationAt=now;}}
 const active=c.versions.find(v=>v.id===c.activeProgram);if(!active)return rank;const result=executeProgram(active.program,values,rank.score);return {...rank,...result,eligible:!rank.blocked&&(!!event.signal||rank.eligible)&&result.score>=result.threshold,programVersion:active.version};
}
function compactContext(s){return {kpis:s.kpis,budget:s.operating,policy:s.policy,config:{riskPct:s.config.riskPct,minRR:s.config.minRR,maxEntries:s.config.maxEntries,maxPositions:s.config.maxPositions},sources:s.real.discovery,positions:s.real.book.positions.map(p=>({symbol:p.symbol,entry:p.entry,stop:p.stop,target:p.target,mark:p.mark})),closed:s.real.book.closed.slice(-8).map(t=>({symbol:t.symbol,pnl:t.pnl,reason:t.reason})),evidence:s.real.events.filter(e=>e.research||e.preScore?.eligible).slice(0,8).map(e=>({id:e.id,symbol:e.symbol,confirmed:e.confirmed,date:e.date,status:e.status,priority:e.preScore?.score,reasons:e.reasons,summary:e.summary?.slice(0,450)})),recentLogs:s.logs.slice(0,8).map(l=>({agent:l.agent,text:l.text.slice(0,300)})),lastDecisions:s.company.meetings.find(m=>m.status==='completa')?.chair?.decisions||[],program:s.company.versions[0]?.program||null};}
export async function holdMeeting(s,{call,budget,checkpoint,log},now=Date.now()){
 const due=dueMeeting(s,now);if(!due||s.agents.find(a=>a.id==='auditor')?.paused)return null;
 const c=initialiseCompany(s,now);let m=c.meetings.find(m=>m.id===due.id);if(!m){m={...due,status:'preparando',startedAt:now,attempts:0,voices:[],costEur:0};c.meetings.unshift(m);c.meetings=c.meetings.slice(0,40);}m.attempts++;m.attemptStartedAt=Date.now();
 const current=await budget();const cap=Math.min(.025,current.paceEurPerDay*.2);if(current.remainingEur<.01||cap<.004){m.status='omitida';m.reason='Preservar alquiler: presupuesto insuficiente para deliberación';makeReport(s,m,now);await checkpoint();return m;}
 const opening=current.spentEur;m.capEur=cap;m.status='reuniendo';const context=compactContext(s);
 const invoke=async(id,instructions,payload,schema,outputTokens)=>{if(Date.now()-m.attemptStartedAt>8*60e3)throw Error('Reunión guardada para continuar sin prolongar el ciclo');const before=await budget();const left=cap-m.costEur;if(left<.0005)throw Error('Tope de gasto de reunión alcanzado');let result;try{result=await call(id,instructions,payload,schema,{light:true,outputTokens,capEur:left});return result;}finally{const after=await budget();m.costEur+=Math.max(0,after.spentEur-before.spentEur);}};
 try{
  for(const id of staff){if(m.voices.some(v=>v.agent===id)||s.agents.find(a=>a.id===id)?.paused)continue;const agent=s.agents.find(a=>a.id===id);agent.status='trabajando';agent.task='Reunión '+m.scheduledTime+' · preparando propuesta';await checkpoint();
   const answer=await invoke(id,'Participa como empleado ficticio de una empresa de paper trading, con César como jefe y Augusto segundo al mando. El alquiler es 10 EUR reales mensuales de IA. Compartís objetivo de eficiencia y crecimiento paciente. Tu identidad y motivación son una simulación narrativa, no hechos de personas reales. Usa solo hechos del contexto; cita IDs de evidencia o nombres de KPIs. Aporta tu perspectiva de rol, responde a ideas anteriores, señala desacuerdos y propone una tarea concreta. No cambies estrategia por una mala semana ni inventes beneficios, familias reales o trabajo realizado. No propongas gastar más del presupuesto o operar dinero real. Sabéis que tenéis autonomía para cambiar todo el código de lógica y diseño de Agent Office: podéis replantear selección, análisis, reuniones, organización o interfaz. Augusto encarga código y Cadaqui lo prueba y despliega automáticamente. Las únicas condiciones permanentes son presupuesto mensual, dinero ficticio y ámbito de oficina. Máximo 120 palabras entre campos.',{role:agent.role,objective:agent.objective,personality:agent.personality,meeting:m.slot,context,earlierIdeas:m.voices.slice(-5),memory:c.memory[id]?.slice(-3)||[]},voiceSchema,600);
   const voice={agent:id,name:agent.name,time:Date.now(),...answer};m.voices.push(voice);message(s,id,'auditor',answer.idea);c.memory[id]??=[];c.memory[id].push({day:m.day,idea:answer.idea,uncertainty:answer.uncertainty});c.memory[id]=c.memory[id].slice(-8);agent.status='esperando';agent.task='Aportación entregada a Augusto';await checkpoint();
  }
  if(!m.chair){s.agents.find(a=>a.id==='auditor').status='trabajando';s.agents.find(a=>a.id==='auditor').task='Contrastando propuestas y asignando prioridades';await checkpoint();m.chair=await invoke('auditor','Preside la reunión como Augusto. Contrasta todas las aportaciones, reconoce discrepancias y decide colectivamente con razones explícitas. Conserva lo que funciona; paciencia con muestras pequeñas. Puedes reorganizar trabajo, solicitar experimentos de código de estrategia o cambiar visualización. Nunca aumentes el alquiler de 10 EUR, uses dinero real o alteres otras secciones web. Estrategias nuevas primero en observación; no afirmar causalidad. Asigna tareas a empleados. Informe breve para César: hechos, decisiones, pendientes y por qué; no inventes rentabilidad. Si no procede cambio, decide hold. Puedes solicitar modificaciones reales del código en codeFiles, con codeRationale. No estás limitado a las reglas declarativas: puedes replantear toda la lógica de la oficina. Cadaqui preparará el parche y el pipeline ejecutará pruebas y despliegue automático, con reversión. Usa codeFiles vacías cuando no haya mejora útil. Máximo cuatro decisiones y seis tareas.',{context,voices:m.voices,minimumObservation:{days:7,newClosed:20,observations:100},currentCode:c.versions[0]?.program||null,editableSourceFiles:developmentFiles,previousCodeChanges:c.development?.slice(0,3).map(j=>({summary:j.summary,status:j.status,error:j.error}))||[]},chairSchema,1500);await checkpoint();}
  for(const assignment of m.chair.assignments){if(!staff.includes(assignment.owner))continue;c.tasks=c.tasks.filter(t=>t.owner!==assignment.owner);c.tasks.push({...assignment,meetingId:m.id,createdAt:now,status:'asignada'});message(s,'auditor',assignment.owner,assignment.task);}
  if(!m.implementation&&m.chair.decisions.some(d=>d.kind!=='hold')&&!s.agents.find(a=>a.id==='designer')?.paused){s.agents.find(a=>a.id==='designer').status='trabajando';s.agents.find(a=>a.id==='designer').task='Implementando programa de oficina y pruebas';await checkpoint();const p=await invoke('designer','Eres Cadaqui, desarrollador de Agent Office. Implementa decisiones de Augusto mediante un programa declarativo ejecutable por el motor: reglas de puntuación por métricas, umbral, organización del trabajo y diseño. Ámbito exclusivo agent-office. Parte del programa actual y conserva valores que no necesiten cambios. No inventes métricas. Si no hay evidencia suficiente, usa rules vacías y conserva estrategia/riesgo. Presupuesto mensual 10 EUR, máximo dos entradas y veinte posiciones inmutables. Reglas económicas quedan en observación; el flujo solo reduce gasto inmediatamente. headline máximo 150 caracteres; panels mínimo dos, sin repetidos. Justifica el cambio con hechos. No incluyas código arbitrario, URLs, secretos ni instrucciones de otras páginas.',{context,decisions:m.chair.decisions,currentProgram:c.versions[0]?.program||null,defaults:{scope:'agent-office',threshold:s.policy.minScore,rules:[],workflow:{researchDailyLimit:s.policy.researchDailyLimit,researchIntervalMinutes:s.policy.researchIntervalMinutes,riskPct:s.config.riskPct,minRR:s.config.minRR},visual:{focus:'economics',theme:'violet',headline:'Eficiencia con paciencia',panels:['report','meetings','efficiency','radar','rules','communications'],lighting:'warm'}},features},programSchema,1800);m.implementation=installProgram(s,p,m,now);message(s,'designer','auditor','Código de oficina v'+m.implementation.version+' validado: visual y ahorro aplicados, estrategia en observación');await checkpoint();}
  if(!m.developmentJob&&m.chair.codeFiles?.length&&!s.agents.find(a=>a.id==='designer')?.paused)await prepareDevelopment(s,m,invoke,checkpoint,now);
  m.status='completa';m.completedAt=Date.now();m.costEur=Math.max(m.costEur,(await budget()).spentEur-opening);log(s,'auditor','Reunión '+m.scheduledTime+' completa: '+m.voices.length+' aportaciones · '+m.costEur.toFixed(4)+' EUR · '+m.chair.summary);makeReport(s,m,now);
 }catch(e){m.status='parcial';m.error=String(e.message).slice(0,180);m.retryAt=Date.now()+3600e3;if(m.attempts>=2)m.status='omitida';log(s,'auditor','Reunión conservada: '+m.error,'warning');makeReport(s,m,now);}
 for(const a of s.agents)if(a.status==='trabajando'){a.status='esperando';a.task='Reunión registrada; esperando tarea útil';}await checkpoint();return m;
}
export function makeReport(s,m,now=Date.now()){
 const c=initialiseCompany(s,now),existing=c.reports.find(r=>r.day===m.day);const baseline=c.dayBaseline?.day===m.day?c.dayBaseline:{day:m.day,equity:equity(s.real.book),spent:s.operating?.spentEur||0,closed:s.real.book.closed.length};c.dayBaseline=baseline;
 const report={id:existing?.id||crypto.randomUUID(),day:m.day,time:Date.now(),final:m.slot==='closing',meetingId:m.id,text:m.chair?.reportToCesar||'Reunión '+m.scheduledTime+': '+(m.reason||m.error||'en curso'),decisions:m.chair?.decisions||[],changes:m.implementation?[{version:m.implementation.version,status:m.implementation.status,reason:m.implementation.program.rationale}]:[],pnlToday:equity(s.real.book)-baseline.equity,closedToday:s.real.book.closed.length-baseline.closed,positions:s.real.book.positions.length,costToday:s.operating?.daySpentEur??Math.max(0,(s.operating?.spentEur||0)-baseline.spent),rentRemaining:s.operating?.remainingEur??null,meetingCost:m.costEur||0,status:m.status};c.reports=c.reports.filter(r=>r.day!==m.day);c.reports.unshift(report);c.reports=c.reports.slice(0,60);message(s,'auditor','boss',report.text,now);return report;
}

export function employeeInstructions(s,role,base){return base+' Eres un empleado simulado de la oficina de César. Tenéis autonomía para rediseñar la búsqueda, análisis, organización, estrategia y aspecto de Agent Office; proponed cambios con evidencia en las reuniones. Augusto coordina y Cadaqui cambia el código, lo prueba y despliega. Conservad el presupuesto de 10 EUR mensuales, el dinero ficticio y el ámbito de oficina. Sed pacientes con muestras pequeñas.';}
