import {prepareDevelopment} from './development.js';
import {developmentFiles} from './office-boundary.js';
import {equity,allocation,id} from './core.js';
import {message} from './governance.js';
import {planningFeedback,catalystReady,pipelineSummary,workflowSettings,validateWorkflowStrategy,analysisEvidenceFingerprint} from './strategy.js';
import {createAdaptation,recordAdaptationObservation,reviewAdaptation,adaptationEntryGuard} from './adaptation.js';
export const madridDay=t=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));
export const staff=['scout','analyst','risk','operator','designer','auditor'];
export const cesarDirective='César: el tiempo corre y los tokens cuestan. La continuidad de esta empresa ficticia depende de conservar el presupuesto de 10 EUR y generar beneficio ficticio para cubrir el alquiler del mes siguiente. Es vuestra responsabilidad organizaros, buscar alternativas cuando una candidata se descarte, resolver bloqueos y preparar dos planes fundamentados para la próxima sesión. No esperéis a que César os diga cada paso: repartid tareas, contrastad puntos de vista y cambiad el flujo o el código de la oficina si mejora la eficiencia. Augusto responde por la coordinación y Cadaqui por las soluciones técnicas. En cada reunión explicad qué habéis conseguido, qué falta, quién lo resuelve y para cuándo. Urgencia serena: actuar sobre bloqueos ahora, evaluar rentabilidad con paciencia; no gastar por aparentar actividad ni inventar oportunidades, beneficios o aprobaciones.';
const obj=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const str={type:'string'},num={type:'number'},strings={type:'array',items:str};
const owner={type:'string',enum:staff};
export const voiceSchema=obj({facts:str,evidence:strings,idea:str,replyTo:str,uncertainty:str,nextTask:str});
export const chairSchema=obj({summary:str,officeStatus:str,concerns:str,expectations:str,goals:{type:'array',maxItems:3,items:obj({title:str,owner,dueDate:str})},decisions:{type:'array',maxItems:4,items:obj({title:str,reason:str,owner,kind:{type:'string',enum:['hold','experiment','workflow','visual']},evidence:strings,successMetric:str,reviewDays:num})},assignments:{type:'array',maxItems:6,items:obj({owner,task:str})},reportToCesar:str,codeFiles:{type:'array',maxItems:2,items:{type:'string',enum:developmentFiles}},codeRationale:str});
export const features=['revenueYoY','netMargin','fcf','debtToEbitda','shareGrowth','pe','pb','roe','return5d','return21d','return63d','relativeVolume','beta1y','averageDollarVolume','marketCap','signalStrength','daysToEvent'];
const ruleSchema=obj({feature:{type:'string',enum:features},op:{type:'string',enum:['gt','lt']},value:num,points:num});
export const programSchema=obj({scope:{type:'string',enum:['agent-office']},rationale:str,threshold:num,rules:{type:'array',maxItems:12,items:ruleSchema},workflow:obj({researchDailyLimit:num,researchIntervalMinutes:num,riskPct:num,minRR:num}),visual:obj({focus:{type:'string',enum:['risk','economics','pipeline']},theme:{type:'string',enum:['amber','violet','mint']},headline:str,panels:{type:'array',items:{type:'string',enum:['efficiency','radar','rules','communications','meetings','report']}},lighting:{type:'string',enum:['day','warm','night']}})});
function economicSettings(p){
 const grouped=new Map();for(const r of p?.rules||[]){const key=JSON.stringify([r.feature,r.op,r.value]);grouped.set(key,(grouped.get(key)||0)+r.points);}
 return {threshold:p?.threshold,rules:[...grouped].filter(([,points])=>points!==0).sort(([a],[b])=>a.localeCompare(b)),riskPct:p?.workflow?.riskPct,minRR:p?.workflow?.minRR};
}
export function hasEconomicChange(s,p,previous=null){
 const before=previous||{policy:s.policy,config:s.config,activeProgram:s.company?.activeProgram},activeId=Object.hasOwn(before,'activeProgram')?before.activeProgram:s.company?.activeProgram,active=s.company?.versions?.find(v=>v.id===activeId);
 const baseline={threshold:active?.program?.threshold??before.policy?.minScore??s.policy?.minScore??45,rules:active?.program?.rules||[],workflow:{riskPct:before.config?.riskPct??s.config.riskPct,minRR:before.config?.minRR??s.config.minRR}};
 return JSON.stringify(economicSettings(p))!==JSON.stringify(economicSettings(baseline));
}
const ownsTrades=(s,id)=>[...(s.real.book.positions||[]),...(s.real.book.closed||[]),...(s.real.book.orders||[]).filter(o=>o.side==='buy')].some(t=>t.adaptationId===id);
export function canReplacePilot(s,proposedProgram=null){const v=s.company?.versions?.find(v=>v.id===s.company.shadowProgram);return !!v&&!ownsTrades(s,v.id)&&(!proposedProgram||hasEconomicChange(s,proposedProgram)&&JSON.stringify(economicSettings(v.program))!==JSON.stringify(economicSettings(proposedProgram)));}
function retireUntradedPilot(s,v,reason,now,replacementId=null){
 v.status=replacementId?'sustituido':'solo flujo y visual';v.gate=reason;v.supersededAt=now;v.supersededBy=replacementId;
 if(v.adaptation){v.adaptation={...v.adaptation,phase:'reverted',revertedAt:now,reviewReason:reason,history:[...(v.adaptation.history||[]),{at:now,phase:'reverted',reason}]};}
 if(s.company.shadowProgram===v.id)s.company.shadowProgram=null;
 for(const e of s.real.events||[])if(e.plan?.adaptationId===v.id&&e.status!=='abierto'){e.previousPlan={...e.plan,withdrawnAt:now,reason};if(e.review)e.previousReview={...e.review,withdrawnAt:now};delete e.plan;delete e.review;e.status='nuevo';e.reasons=['Plan retirado al sustituir un piloto sin operaciones; requiere nueva valoración'];}
}
export function initialiseCompany(s,now=Date.now()){
 s.company??={meetings:[],reports:[],versions:[],tasks:[],memory:{},activeProgram:null,shadowProgram:null,version:0};const c=s.company;c.memory??={};
 c.ownerDirective=cesarDirective;
 if(!c.adaptationDirectiveDelivered){c.adaptationDirectiveDelivered=now;for(const id of staff)message(s,'boss',id,'César autoriza aprendizaje y reinvención: plantead hipótesis concretas, modificad estrategia y probad pilotos sin esperar cierres previos. Podéis ajustar riesgo entre 0,1% y 2% y beneficio/riesgo mínimo entre 1 y 8; el piloto sube como máximo 0,25 puntos de riesgo respecto a la base. Usad métricas del embudo, datos y resultados reales; Augusto decide, María cuestiona y Cadaqui implementa. Conservad 10 EUR de IA, dinero ficticio, dos entradas diarias, veinte posiciones y el ámbito de oficina. Registrad objetivos, cambios, costes, revisión y reversión.',now);}
 if(!c.economicPilotMigration){c.economicPilotMigration=1;const v=c.versions.find(v=>v.id===c.shadowProgram&&['observación','piloto'].includes(v.status));if(v&&!hasEconomicChange(s,v.program,v.previous)){v.economicChange=false;if(!ownsTrades(s,v.id))retireUntradedPilot(s,v,'Programa equivalente a la estrategia base: conservar flujo e interfaz, sin ocupar un piloto',now);else v.gate='Programa equivalente con operaciones propias registradas; conservar procedencia y revisión sin borrar resultados';}}
 if(!c.adaptationMigration&&s.operating&&Number.isFinite(s.operating.spentEur)){c.adaptationMigration=1;const v=c.versions.find(v=>v.id===c.shadowProgram&&v.status==='observación');if(v){v.adaptation=createAdaptation(v,{book:s.real.book,aiEur:s.operating.spentEur,aiMonth:s.operating.month},now);v.status='piloto';v.gate=v.economicChange===false?'Programa equivalente con operaciones propias registradas; conservar procedencia y revisión sin borrar resultados':'Piloto limitado habilitado; aprendizaje con resultados reales, sin exigir cierres previos';}}

 if(!c.ownerDirectiveDelivered){c.ownerDirectiveDelivered=now;for(const id of staff)message(s,'boss',id,cesarDirective,now);}
 for(const m of c.meetings)for(const v of m.voices||[])if(v.agent==='operator')v.name=s.agents.find(a=>a.id==='operator')?.name||'Yari';
 // One migration retry for a chair response truncated earlier today. Preserve paid voices and costs.
 if(!c.chairRecoveryMigration){c.chairRecoveryMigration=1;const m=c.meetings.find(m=>m.day===madridDay(now)&&m.status==='omitida'&&!m.chair&&m.voices?.length===staff.length&&m.responses?.length===m.voices.length&&/respuesta de IA incompleta|truncad|max_output_tokens/i.test(m.error||''));
  if(m){m.status='parcial';m.retryAt=now;m.chairRecoveryPending=true;m.chairRecoveryGrantedAt=now;}
 }
 return c;
}
export function dueMeeting(s,now=Date.now()){
 const c=initialiseCompany(s,now),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(now)).split(':').map(Number),minutes=parts[0]*60+parts[1],day=madridDay(now);
 for(const [slot,start] of [['planning',660],['closing',1350]]){if(minutes<start)continue;const id=day+':'+slot,m=c.meetings.find(m=>m.id===id);if(!m)return {id,day,slot,scheduledTime:slot==='planning'?'11:00':'22:30'};if(['completa','omitida'].includes(m.status))continue;if((m.attempts<2||m.chairRecoveryPending)&&(!m.retryAt||now>=m.retryAt))return m;}
 return null;
}
export function validateProgram(p){
 if(!p||p.scope!=='agent-office'||typeof p.rationale!=='string'||p.rationale.length>1500||!Number.isFinite(p.threshold)||p.threshold<30||p.threshold>90)throw Error('Programa fuera del ámbito o umbral inválido');
 if(!Array.isArray(p.rules)||p.rules.length>12)throw Error('Demasiadas reglas');for(const r of p.rules)if(!features.includes(r.feature)||!['gt','lt'].includes(r.op)||!Number.isFinite(r.value)||Math.abs(r.value)>1e12||!Number.isFinite(r.points)||Math.abs(r.points)>20)throw Error('Regla no válida');
 const w=p.workflow;if(!w||!Number.isInteger(w.researchDailyLimit)||w.researchDailyLimit<1||w.researchDailyLimit>12||!Number.isInteger(w.researchIntervalMinutes)||w.researchIntervalMinutes<30||w.researchIntervalMinutes>240||!Number.isFinite(w.riskPct)||w.riskPct<.1||w.riskPct>2||!Number.isFinite(w.minRR)||w.minRR<1||w.minRR>8)throw Error('Flujo fuera de los límites del laboratorio');
 const v=p.visual;if(!v||!['risk','economics','pipeline'].includes(v.focus)||!['amber','violet','mint'].includes(v.theme)||!['day','warm','night'].includes(v.lighting)||typeof v.headline!=='string'||v.headline.length>200||!Array.isArray(v.panels)||v.panels.length<2||new Set(v.panels).size!==v.panels.length||v.panels.some(x=>!['efficiency','radar','rules','communications','meetings','report'].includes(x)))throw Error('Diseño de oficina inválido');return p;
}
export function executeProgram(p,values,baseScore){validateProgram(p);let score=baseScore;for(const r of p.rules){const v=values[r.feature];if(Number.isFinite(v)&&(r.op==='gt'?v>r.value:v<r.value))score+=r.points;}return {score:Math.max(0,Math.min(100,Math.round(score))),threshold:p.threshold};}
export function testProgram(p){validateProgram(p);const empty=executeProgram(p,{},0),strong=executeProgram(p,{revenueYoY:.2,fcf:1e6,relativeVolume:2,marketCap:300e6},60);if(![empty.score,strong.score].every(Number.isFinite))throw Error('Prueba de programa fallida');return ['ámbito de oficina','métricas ausentes','puntuación finita','presupuesto inmutable','límites de riesgo','sin ejecución arbitraria'];}
export function installProgram(s,p,meeting,now=Date.now()){
 validateProgram(p);const c=initialiseCompany(s,now),tests=testProgram(p),previous={policy:{...s.policy},config:{riskPct:s.config.riskPct,minRR:s.config.minRR},activeProgram:c.activeProgram,ui:c.ui||null};
 // Operational and visual changes can run immediately. Strategy is an experiment first.
 const operational={researchDailyLimit:p.workflow.researchDailyLimit,researchIntervalMinutes:p.workflow.researchIntervalMinutes};
 c.evidenceProtocol=measureEvidence(s,now);c.strategy=validateWorkflowStrategy(operational,workflowSettings(s));Object.assign(s.policy,operational);s.policy.version++;c.ui=p.visual;
 const economicChange=hasEconomicChange(s,p,previous),version={id:crypto.randomUUID(),version:++c.version,time:now,meetingId:meeting.id,program:p,source:'// Programa autónomo de Agent Office. Interpretado por el motor validado.\nexport default '+JSON.stringify(p,null,2)+';\n',previous,baseline:{closed:s.real.book.closed.length,equity:equity(s.real.book),drawdown:s.real.book.maxDrawdown||0},tests,status:'piloto',economicChange,observations:0,lastObservationAt:0};
 const prior=c.versions.find(v=>v.id===c.shadowProgram),samePilot=prior&&JSON.stringify(economicSettings(prior.program))===JSON.stringify(economicSettings(p));
 if(!economicChange){version.status='solo flujo y visual';version.gate='Sin cambios económicos respecto a la estrategia vigente; flujo e interfaz aplicados sin piloto';}
 else if(samePilot){version.status='solo flujo y visual';version.gate='Hipótesis económica ya en piloto; conservar plazo, observaciones y costes';}
 else if(c.shadowProgram&&!canReplacePilot(s)){version.status='solo flujo y visual';version.gate='Hay operaciones propias del piloto previo; conservar su revisión antes de sustituirlo';}
 else {if(prior)retireUntradedPilot(s,prior,'Hipótesis sustituida antes de operar; no es un resultado de rentabilidad',now,version.id);version.adaptation=createAdaptation(version,{book:s.real.book,aiEur:s.operating?.spentEur,aiMonth:s.operating?.month},now);c.shadowProgram=version.id;version.gate='Piloto validado: hasta dos posiciones y 10% del patrimonio; rentabilidad aún no demostrada';}c.versions.unshift(version);c.versions=c.versions.filter((v,i)=>i<20||v.id===c.shadowProgram||v.id===c.activeProgram);return version;
}
export function strategyExperiments(s){return (s.company?.versions||[]).filter(v=>v.adaptation).slice(0,6).map(v=>({id:v.id,version:v.version,phase:v.adaptation.phase,reason:v.adaptation.reviewReason||v.gate,rationale:v.program.rationale,threshold:v.program.threshold,rules:v.program.rules,requested:v.adaptation.requested,effective:v.adaptation.effectiveSettings,metrics:v.adaptation.metrics,missingEvidence:v.adaptation.missingEvidence||[]}));}
export function candidateStrategy(s,event){
 const id=event.plan?event.plan.adaptationId:event.preScore?.adaptationId,v=(s.company?.versions||[]).find(v=>v.id===id),a=v?.adaptation;
 return {config:{...s.config,...(a?.phase==='pilot'?a.effectiveSettings:{})},adaptationId:a&&['pilot','active'].includes(a.phase)?a.id:null,strategyVersion:a&&['pilot','active'].includes(a.phase)?v.version:null};
}
export function candidateStrategyGuard(s,event,now=Date.now(),allocationEur=allocation(s.real.book)){
 const id=event.plan?.adaptationId;if(!id)return {ok:true,reasons:[]};const v=s.company.versions.find(v=>v.id===id);
 if(!v?.adaptation)return {ok:false,reasons:['Experimento del plan ya no disponible; requiere nueva valoración']};
 return adaptationEntryGuard(v.adaptation,{book:s.real.book,allocationEur},now);
}
export function observeProgram(s,now=Date.now()){
 const c=initialiseCompany(s,now);c.evidenceProtocol=measureEvidence(s,now);
 for(const v of c.versions.filter(v=>v.adaptation&&['pilot','active'].includes(v.adaptation.phase))){
  const before=v.adaptation.phase;v.adaptation=reviewAdaptation(v.adaptation,{book:s.real.book,aiEur:s.operating?.spentEur,aiMonth:s.operating?.month},now);v.gate=v.adaptation.reviewReason;v.observations=v.adaptation.observations.length;
  if(before===v.adaptation.phase)continue;
  if(v.adaptation.phase==='active'){c.activeProgram=v.id;c.shadowProgram=null;v.status='activo';v.activatedAt=now;s.policy.minScore=v.program.threshold;c.strategy=validateWorkflowStrategy({minScore:v.program.threshold,...v.adaptation.effectiveSettings},workflowSettings(s));s.config.riskPct=v.adaptation.effectiveSettings.riskPct;s.config.minRR=v.adaptation.effectiveSettings.minRR;message(s,'auditor','boss','Estrategia v'+v.version+' activada con evidencia preliminar: '+v.gate,now);}
  else if(v.adaptation.phase==='reverted'){v.status='revertido';v.rollbackAt=now;if(c.shadowProgram===v.id)c.shadowProgram=null;if(c.activeProgram===v.id){c.activeProgram=c.versions.find(p=>p.id===v.previous.activeProgram&&p.adaptation?.phase==='active')?.id||null;if(s.config.riskPct===v.adaptation.effectiveSettings.riskPct)s.config.riskPct=v.previous.config.riskPct;if(s.config.minRR===v.adaptation.effectiveSettings.minRR)s.config.minRR=v.previous.config.minRR;if(s.policy.minScore===v.program.threshold)s.policy.minScore=v.previous.policy.minScore;c.strategy=validateWorkflowStrategy({minScore:s.policy.minScore,riskPct:s.config.riskPct,minRR:s.config.minRR},workflowSettings(s));}
   for(const e of s.real.events)if(e.plan?.adaptationId===v.id&&e.status!=='abierto'){e.previousPlan={...e.plan,withdrawnAt:now,reason:v.gate};delete e.plan;delete e.review;e.status='nuevo';e.reasons=['Plan retirado por reversión del experimento; requiere nueva valoración'];}
   message(s,'auditor','boss','Estrategia v'+v.version+' revertida: '+v.gate+'. Las posiciones abiertas conservan sus stops.',now);
  }
 }
}
export function augmentScore(s,event,asset,profile,rank,now=Date.now()){
 const c=initialiseCompany(s,now),values={...profile?.fundamentals?.metrics,...profile?.market,marketCap:asset.marketCap,signalStrength:event.signal?.strength||0,daysToEvent:event.date?(Date.parse(event.date)-now)/864e5:null};
 const active=c.versions.find(v=>v.id===c.activeProgram),base=active?{...rank,...executeProgram(active.program,values,rank.score),programVersion:active.version,adaptationId:active.adaptation?.id}:rank;
 if(active)base.eligible=!rank.blocked&&(!!event.signal||rank.eligible)&&base.score>=base.threshold;
 const pilot=c.versions.find(v=>v.id===c.shadowProgram&&v.adaptation?.phase==='pilot');if(!pilot)return base;
 const scored=executeProgram(pilot.program,values,rank.score),eligible=!rank.blocked&&(!!event.signal||rank.eligible)&&scored.score>=scored.threshold;
 const fingerprint=id(analysisEvidenceFingerprint({real:{profiles:{[event.symbol]:profile}}},event),JSON.stringify(features.filter(f=>f!=='daysToEvent').map(f=>[f,values[f]??null])),base.score,scored.score);
 pilot.adaptation=recordAdaptationObservation(pilot.adaptation,{eventId:event.id,evidenceFingerprint:fingerprint,at:now,baselineEligible:!!base.eligible,pilotEligible:eligible,baselineScore:base.score,pilotScore:scored.score});pilot.observations=pilot.adaptation.observations.length;
 const capacity=adaptationEntryGuard(pilot.adaptation,{book:s.real.book,allocationEur:allocation(s.real.book)},now);
 event.experiment={version:pilot.version,...scored,eligible,adaptationId:pilot.id,observationOnly:!capacity.ok};
 return capacity.ok?{...base,...scored,eligible,programVersion:pilot.version,adaptationId:pilot.id}:base;
}
export function compactContext(s,now=Date.now()){return {snapshotAt:new Date(now).toISOString(),ownerDirective:s.company.ownerDirective||cesarDirective,pipeline:pipelineSummary(s,now),sessionPreparation:s.company.sessionPlan||null,strategy:workflowSettings(s),experiments:strategyExperiments(s),planningFeedback:planningFeedback(s),learning:s.kpis?.learning||null,employeeInitiatives:(s.company.employeeIdeas||[]).slice(0,6),individualDecisions:s.company.agency?.journal?.slice(0,6)||[],riskNotes:(s.company.riskNotes||[]).slice(0,4),evidenceProtocol:measureEvidence(s,now),kpis:s.kpis,budget:s.operating,policy:s.policy,config:{riskPct:s.config.riskPct,minRR:s.config.minRR,maxEntries:s.config.maxEntries,maxPositions:s.config.maxPositions},sources:s.real.discovery,positions:s.real.book.positions.map(p=>({symbol:p.symbol,entry:p.entry,stop:p.stop,target:p.target,mark:p.mark})),closed:s.real.book.closed.slice(-8).map(t=>({symbol:t.symbol,pnl:t.pnl,reason:t.reason})),evidence:s.real.events.filter(e=>e.research||e.preScore?.eligible).slice(0,8).map(e=>({id:e.id,symbol:e.symbol,confirmed:e.confirmed,date:e.date,timing:e.timing||'scheduled',plan:!!e.plan,review:e.review?.approve,status:e.status,priority:e.preScore?.score,reasons:e.reasons,summary:e.summary?.slice(0,450)})),recentLogs:s.logs.slice(0,8).map(l=>({agent:l.agent,text:l.text.slice(0,300)})),lastDecisions:s.company.meetings.find(m=>m.status==='completa')?.chair?.decisions||[],program:s.company.versions[0]?.program||null};}
export async function holdMeeting(s,{call,budget,checkpoint,log},now=Date.now()){
 const due=dueMeeting(s,now);if(!due||s.agents.find(a=>a.id==='auditor')?.paused)return null;
 const c=initialiseCompany(s,now);let m=c.meetings.find(m=>m.id===due.id);if(!m){m={...due,status:'preparando',startedAt:now,attempts:0,voices:[],costEur:0};c.meetings.unshift(m);c.meetings=c.meetings.slice(0,40);}m.attempts++;if(m.chairRecoveryPending){m.chairRecoveryPending=false;m.chairRecoveryAttemptedAt=now;}m.attemptStartedAt=Date.now();
 const current=await budget();const cap=Math.min(.025,current.paceEurPerDay*.2);if(current.remainingEur<.01||cap<.004){m.status='omitida';m.reason='Preservar alquiler: presupuesto insuficiente para deliberación';makeReport(s,m,now);await checkpoint();return m;}
 const opening=current.spentEur;m.capEur=cap;m.status='reuniendo';const context=compactContext(s,now);
 const invoke=async(id,instructions,payload,schema,outputTokens)=>{if(Date.now()-m.attemptStartedAt>8*60e3)throw Error('Reunión guardada para continuar sin prolongar el ciclo');const before=await budget();const left=cap-m.costEur;if(left<.0005)throw Error('Tope de gasto de reunión alcanzado');let result;try{result=await call(id,instructions,payload,schema,{light:true,outputTokens,capEur:left});return result;}finally{const after=await budget();m.costEur+=Math.max(0,after.spentEur-before.spentEur);}};
 try{
  for(const id of staff){if(m.voices.some(v=>v.agent===id)||s.agents.find(a=>a.id===id)?.paused)continue;const agent=s.agents.find(a=>a.id===id);agent.status='trabajando';agent.task='Reunión '+m.scheduledTime+' · preparando propuesta';await checkpoint();
   const answer=await invoke(id,'Participa como empleado ficticio de una empresa de paper trading, con César como jefe y Augusto segundo al mando. El alquiler es 10 EUR reales mensuales de IA. Compartís objetivo de eficiencia y crecimiento paciente. Tu identidad y motivación son una simulación narrativa, no hechos de personas reales. Usa solo hechos del contexto; cita IDs de evidencia o nombres de KPIs. Aporta tu perspectiva de rol, formula primero una propuesta propia e independiente con una acción concreta y una alternativa. No copies el consenso de reuniones anteriores: si hay un cuello de botella de fuentes, datos o código, propone cómo resolverlo ahora sin esperar cierres. El debate posterior contrastará las ideas. No cambies estrategia por una mala semana ni inventes beneficios, familias reales o trabajo realizado. No propongas gastar más del presupuesto o operar dinero real. Sabéis que tenéis autonomía para cambiar todo el código de lógica y diseño de Agent Office: podéis replantear selección, análisis, reuniones, organización o interfaz. Augusto encarga código y Cadaqui lo prueba y despliega automáticamente. Las únicas condiciones permanentes son presupuesto mensual, dinero ficticio y ámbito de oficina. Fuera de sesión y fines de semana podéis investigar fuentes, comparar empresas y preparar planes con referencias fechadas; nunca simular compras sin cotización válida. Propón esas tareas por iniciativa propia si son útiles y usa caché antes de nuevas llamadas. El personaje puede mostrar preocupación moderada por el alquiler y humor breve, sin urgencia que aumente el riesgo ni gastar para aparentar actividad. Máximo 120 palabras entre campos.',{role:agent.role,objective:agent.objective,personality:agent.personality,meeting:m.slot,context,earlierIdeas:[],memory:c.memory[id]?.slice(-3)||[]},voiceSchema,600);
   const voice={agent:id,name:agent.name,time:Date.now(),...answer};m.voices.push(voice);message(s,id,'auditor',answer.idea);c.memory[id]??=[];c.memory[id].push({day:m.day,idea:answer.idea,uncertainty:answer.uncertainty});c.memory[id]=c.memory[id].slice(-8);agent.status='esperando';agent.task='Aportación entregada a Augusto';await checkpoint();
  }
  m.responses??=[];for(const voice of m.voices){if(m.responses.some(r=>r.agent===voice.agent))continue;const response=await invoke(voice.agent,'Segunda ronda del debate. Contrasta tu idea independiente con las propuestas de los demás. Puedes apoyarlas, cuestionarlas, combinarlas o proponer una alternativa concreta. Señala qué decisión tomarías tú, qué evidencia falta y qué experimento ejecutarías. No estás obligado a discrepar ni a repetir el consenso. Máximo 65 palabras entre campos.',{context,ownIdea:voice,allIdeas:m.voices},voiceSchema,350);m.responses.push({agent:voice.agent,name:voice.name,time:Date.now(),...response});message(s,voice.agent,'auditor',response.replyTo||response.idea);await checkpoint();}
  if(!m.chair){s.agents.find(a=>a.id==='auditor').status='trabajando';s.agents.find(a=>a.id==='auditor').task='Contrastando propuestas y asignando prioridades';await checkpoint();m.chair=await invoke('auditor','Preside la reunión como Augusto. Contrasta todas las aportaciones, reconoce discrepancias y decide colectivamente con razones explícitas. Conserva lo que funciona; paciencia con muestras pequeñas. Puedes reorganizar trabajo, solicitar experimentos de código de estrategia o cambiar visualización. Nunca aumentes el alquiler de 10 EUR, uses dinero real o alteres otras secciones web. Estrategias nuevas mediante pilotos limitados que pueden empezar tras validar el cambio, sin esperar cierres previos; no afirmar causalidad. Podéis reinventar selección, fuentes, análisis y coordinación, y aumentar o reducir riesgo con hipótesis medibles. No confundáis ausencia de operaciones con prueba de que la estrategia es mala: investigad el embudo y proponed alternativas concretas. Asigna tareas a empleados. Informe breve para César: hechos, decisiones, pendientes y por qué; no inventes rentabilidad. Si no procede cambio, decide hold. Puedes solicitar modificaciones reales del código en codeFiles, con codeRationale. No estás limitado a las reglas declarativas: puedes replantear toda la lógica de la oficina. Cadaqui preparará el parche y el pipeline ejecutará pruebas y despliegue automático, con reversión. Usa codeFiles vacías cuando no haya mejora útil. Las mejoras de fuentes, resolución de errores, costes, coordinación e interfaz no requieren esperar veinte cierres: puedes ejecutarlas con pruebas cuando sean útiles. Evita un hold que bloquee resolver un cuello de botella comprobado. Reserva la paciencia estadística para afirmar rentabilidad o elevar riesgo. Resume officeStatus, concerns y expectations en una frase cada campo, basadas en hechos e incertidumbres. Propón hasta tres objetivos concretos de corto plazo con responsable y dueDate YYYY-MM-DD futura, usando snapshotAt como fecha de referencia. No inventes tareas hechas ni objetivos de rentabilidad garantizada. Prioriza investigación y planes fuera de sesión cuando sea útil; no obligues a gastar tokens o comprar. Máximo 350 palabras en toda la respuesta, incluidos todos los campos. Hasta cuatro decisiones y seis tareas; frases cortas y hasta dos IDs de evidencia por decisión. No repitas estadísticas en varios campos. Las asignaciones deben mover trabajo útil de la cola ahora y preparar la próxima sesión; no pongas a Pedro a esperar siete días para estudiar candidatas disponibles.',{context,voices:m.voices,responses:m.responses,pilotPolicy:{maxPositions:2,maxExposurePct:10,riskStepPct:.25,riskRange:[.1,2],minRRRange:[1,8],preliminaryPromotion:{days:3,ownClosed:3},maxDays:21},currentCode:c.versions[0]?.program||null,editableSourceFiles:developmentFiles,previousCodeChanges:c.development?.slice(0,3).map(j=>({summary:j.summary,status:j.status,error:j.error}))||[]},chairSchema,2300);await checkpoint();}
  for(const assignment of m.chair.assignments){if(!staff.includes(assignment.owner))continue;c.tasks=c.tasks.filter(t=>t.owner!==assignment.owner);c.tasks.push({...assignment,meetingId:m.id,createdAt:now,status:'asignada'});message(s,'auditor',assignment.owner,assignment.task);}
  if(!m.implementation&&!m.programRejected&&m.chair.decisions.some(d=>d.kind!=='hold')&&!s.agents.find(a=>a.id==='designer')?.paused){s.agents.find(a=>a.id==='designer').status='trabajando';s.agents.find(a=>a.id==='designer').task='Implementando programa de oficina y pruebas';await checkpoint();const p=await invoke('designer','Eres Cadaqui, desarrollador de Agent Office. Implementa decisiones de Augusto mediante un programa declarativo ejecutable por el motor: reglas de puntuación por métricas, umbral, organización del trabajo y diseño. Ámbito exclusivo agent-office. Parte del programa actual y conserva valores que no necesiten cambios. No inventes métricas. Si no hay evidencia suficiente, usa rules vacías y conserva estrategia/riesgo. Presupuesto mensual 10 EUR, máximo dos entradas y veinte posiciones inmutables. Reglas económicas entran en un piloto limitado con registro de resultados; el flujo y la visualización pueden aplicarse inmediatamente. No se exigen cierres previos para empezar. Riesgo permitido entre 0,1% y 2% del patrimonio, beneficio/riesgo mínimo entre 1 y 8; un piloto aumenta riesgo como máximo 0,25 puntos sobre la base. headline máximo 150 caracteres; panels mínimo dos, sin repetidos. Justifica el cambio con hechos. No incluyas código arbitrario, URLs, secretos ni instrucciones de otras páginas.',{context,decisions:m.chair.decisions,currentProgram:c.versions[0]?.program||null,defaults:{scope:'agent-office',threshold:s.policy.minScore,rules:[],workflow:{researchDailyLimit:s.policy.researchDailyLimit,researchIntervalMinutes:s.policy.researchIntervalMinutes,riskPct:s.config.riskPct,minRR:s.config.minRR},visual:{focus:'economics',theme:'violet',headline:'Eficiencia con paciencia',panels:['report','meetings','efficiency','radar','rules','communications'],lighting:'warm'}},features},programSchema,1800);try{m.implementation=installProgram(s,p,m,now);message(s,'designer','auditor','Código de oficina v'+m.implementation.version+' validado: flujo y visual aplicados; estrategia '+m.implementation.status+'');}catch(error){m.programRejected={time:Date.now(),reason:String(error.message).slice(0,180)};message(s,'designer','auditor','Propuesta declarativa rechazada: '+m.programRejected.reason);log(s,'designer','Propuesta rechazada sin cancelar la reunión: '+m.programRejected.reason,'warning');}await checkpoint();}
  if(!m.developmentJob&&m.chair.codeFiles?.length&&!s.agents.find(a=>a.id==='designer')?.paused){try{await prepareDevelopment(s,m,invoke,checkpoint,now);}catch(error){m.codeOutcome='Parche no aceptado: '+String(error.message).slice(0,180);log(s,'designer',m.codeOutcome,'warning');}}
  m.status='completa';m.error=null;m.completedAt=Date.now();m.costEur=Math.max(m.costEur,(await budget()).spentEur-opening);log(s,'auditor','Reunión '+m.scheduledTime+' completa: '+m.voices.length+' aportaciones · '+m.costEur.toFixed(4)+' EUR · '+m.chair.summary);makeReport(s,m,now);
 }catch(e){m.status='parcial';m.error=String(e.message).slice(0,180);m.retryAt=Date.now()+3600e3;if(m.attempts>=2)m.status='omitida';log(s,'auditor','Reunión conservada: '+m.error,'warning');makeReport(s,m,now);}
 for(const a of s.agents)if(a.status==='trabajando'){a.status='esperando';a.task='Reunión registrada; esperando tarea útil';}await checkpoint();return m;
}
export function makeReport(s,m,now=Date.now()){
 const c=initialiseCompany(s,now),existing=c.reports.find(r=>r.day===m.day);const baseline=c.dayBaseline?.day===m.day?c.dayBaseline:{day:m.day,equity:equity(s.real.book),spent:s.operating?.spentEur||0,closed:s.real.book.closed.length};c.dayBaseline=baseline;
 const report={id:existing?.id||crypto.randomUUID(),day:m.day,time:Date.now(),final:m.slot==='closing',meetingId:m.id,text:(m.chair?.reportToCesar||'Reunión '+m.scheduledTime+': '+(m.reason||m.error||'en curso'))+(m.programRejected?'\nPropuesta declarativa rechazada: '+m.programRejected.reason:'')+(m.codeOutcome?'\n'+m.codeOutcome:''),decisions:m.chair?.decisions||[],changes:m.implementation?[{version:m.implementation.version,status:m.implementation.status,reason:m.implementation.program.rationale}]:[],pnlToday:equity(s.real.book)-baseline.equity,closedToday:s.real.book.closed.length-baseline.closed,positions:s.real.book.positions.length,costToday:s.operating?.daySpentEur??Math.max(0,(s.operating?.spentEur||0)-baseline.spent),rentRemaining:s.operating?.remainingEur??null,meetingCost:m.costEur||0,status:m.status};c.reports=c.reports.filter(r=>r.day!==m.day);c.reports.unshift(report);c.reports=c.reports.slice(0,60);message(s,'auditor','boss',report.text,now);return report;
}

export function employeeInstructions(s,role,base){return base+' '+cesarDirective+' Eres un empleado simulado de la oficina de César. Tenéis autonomía para rediseñar la búsqueda, análisis, organización, estrategia y aspecto de Agent Office; proponed cambios con evidencia en las reuniones. Augusto coordina y Cadaqui cambia el código, lo prueba y despliega. Conservad el presupuesto de 10 EUR mensuales, el dinero ficticio y el ámbito de oficina. Cada uno conserva memoria, criterio propio y capacidad de proponer iniciativas y cuestionar a los demás. Vuestra continuidad es una ficción empresarial: 10.000 unidades representan el alquiler máximo mensual de 10 EUR de IA; objetivo cubrirlo con 10.000 EUR de beneficio ficticio mensual a la escala 1.000:1. Agotar el presupuesto suspende la IA; perder el capital impide seguir comprando. Interpretad preocupación, miedo ficticio a desaparecer y motivación como parte del personaje, no sentimientos o familias reales. Esta meta es ambiciosa, no una rentabilidad garantizada: podéis aumentar riesgo gradualmente y cambiar estrategia con hipótesis y pruebas; no aumentéis riesgo únicamente por miedo, no forcéis compras, no inventéis datos ni resultados y no ocultéis pérdidas. Buscad soluciones creativas al trabajo y a los costes con autonomía; sed pacientes con muestras pequeñas.';}

export function measureEvidence(s,now=Date.now()){
 const rows=s.real.events.filter(e=>e.research||e.preScore?.eligible).map(e=>{
  const primary=e.confirmed===true&&e.sources?.length>0,timing=e.timing??e.research?.timing??'scheduled',ready=catalystReady(e,now),status=ready?'elegible':'pausada';
  const reason=!primary?'Sin evidencia primaria consultada y confirmada':!ready?(timing==='announced'?'Sin publicación primaria fechada en los últimos siete días':'Sin fecha futura dentro de 45 días'):(timing==='announced'?'Anuncio primario reciente contrastado; horizonte de valoración por decidir':'Fuente primaria y fecha futura contrastadas');
  return {id:e.id,symbol:e.symbol,status,timing,date:e.date,reason,costEur:Number.isFinite(e.research?.costEur)?e.research.costEur:null,investigated:!!e.research};
 });
 const groups=['elegible','pausada'].map(status=>{const members=rows.filter(r=>r.status===status),known=members.filter(r=>r.costEur!==null);return {status,count:members.length,knownCostEur:known.reduce((n,r)=>n+r.costEur,0),costed:known.length,unknownCosts:members.filter(r=>r.investigated&&r.costEur===null).length};});
 return {at:now,rows:rows.slice(0,30),count:rows.length,groups,observationOnly:true,note:'Observación de evidencia, no aprobación de compra. Se distingue evento futuro de anuncio ya publicado. Costes por candidata solo cuando están registrados; gastos anteriores sin desglose permanecen desconocidos.'};
}
