import {developmentFiles,validateEdits} from './office-boundary.js';
export const patchSchema={type:'object',properties:{summary:{type:'string'},edits:{type:'array',maxItems:6,items:{type:'object',properties:{file:{type:'string',enum:developmentFiles},baseSha:{type:'string'},find:{type:'string'},replace:{type:'string'}},required:['file','baseSha','find','replace'],additionalProperties:false}}},required:['summary','edits'],additionalProperties:false};
export async function prepareDevelopment(s,meeting,invoke,checkpoint,now=Date.now()){
 const c=s.company;if(!meeting.chair?.codeFiles?.length||c.lastCodeDay===meeting.day||c.development?.some(j=>['queued','running'].includes(j.status)))return null;
 const requested=[...new Set(meeting.chair.codeFiles)].filter(p=>developmentFiles.includes(p)).slice(0,2);if(!requested.length)return null;const sources=[];
 for(const path of requested){const r=await fetch('https://api.github.com/repos/CesarSGZ/CesarHomeLab/contents/'+path,{headers:{'User-Agent':'Cesar-Agent-Office','Accept':'application/vnd.github+json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Código fuente no disponible HTTP '+r.status);const j=await r.json(),source=new TextDecoder().decode(Uint8Array.from(atob(j.content.replace(/\s/g,'')),c=>c.charCodeAt(0)));if(source.length>65000)throw Error('Archivo demasiado grande');sources.push({path,sha:j.sha,source});}
 const answer=await invoke('designer','Implementa el cambio de código acordado por los empleados. Solo puedes editar los archivos suministrados de Agent Office. Devuelve entre una y seis sustituciones exactas find/replace; find debe aparecer una sola vez en la versión actual y baseSha debe ser el sha suministrado. No hagas cambios decorativos sin utilidad explicada. Puedes replantear la lógica de coordinación, reuniones, análisis, selección, métricas o visualización. Mantén exportaciones que usa el motor y las condiciones de César: 10 EUR reales/mes, dinero ficticio, sin otra sección web. No incluyas secretos, nuevas dependencias, código de procesos/archivos del host, eval/Function, importaciones dinámicas, acceso global, JavaScript URLs o llamadas a otros servicios privados. La contabilidad y precios originales son de solo lectura. No debilites las pruebas o validaciones. El pipeline ejecutará pruebas en un contenedor sin red y desplegará o revertirá. Responde edits vacías si no hay un cambio útil y verificable.',{decisions:meeting.chair.decisions,rationale:meeting.chair.codeRationale,sources,previousFailures:c.development?.filter(j=>j.status==='rejected').slice(0,2).map(j=>({summary:j.summary,error:j.error}))||[]},patchSchema,4500);
 if(!answer.edits.length){meeting.codeOutcome='Cadaqui no encontró un parche útil';return null;}validateEdits(answer.edits);for(const e of answer.edits)if(!sources.some(f=>f.path===e.file&&f.sha===e.baseSha))throw Error('Parche no corresponde a la fuente leída');
 const job={id:crypto.randomUUID(),meetingId:meeting.id,time:now,status:'queued',summary:answer.summary.slice(0,1000),edits:answer.edits};c.development??=[];c.development.unshift(job);c.development=c.development.slice(0,30);c.lastCodeDay=meeting.day;meeting.developmentJob=job.id;meeting.codeOutcome='Parche de código en cola: pruebas, commit y despliegue automáticos';await checkpoint();return job;
}
export async function authorisedDeveloper(request,env){const bearer=request.headers.get('authorization')||'';if(!bearer.startsWith('Bearer ')||bearer.length>300)return false;const row=await env.CONTROL_DB.prepare('SELECT token_hash FROM trading_dev_auth WHERE id=1').first();if(!row)return false;const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(bearer.slice(7)));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')===row.token_hash;}
export function developmentAction(s,body,now=Date.now()){
 const jobs=s.company?.development||[];if(body.action==='lease'){const job=jobs.find(j=>j.status==='queued'||j.status==='running'&&j.leaseUntil<now);if(!job)return {ok:true,job:null};validateEdits(job.edits);job.status='running';job.lease=crypto.randomUUID();job.leaseUntil=now+20*60e3;return {ok:true,job};}
 if(body.action==='complete'){const job=jobs.find(j=>j.id===body.id);if(!job||job.lease!==body.lease||job.status!=='running')throw Error('Trabajo o lease inválidos');if(!['applied','rejected'].includes(body.status))throw Error('Estado inválido');job.status=body.status;job.completedAt=now;job.commit=/^[a-f0-9]{40}$/.test(body.commit||'')?body.commit:null;job.error=String(body.error||'').slice(0,1500);const text='Código '+(job.status==='applied'?'aplicado y desplegado':'rechazado o revertido')+': '+job.summary+(job.error?' · '+job.error:'');s.logs.unshift({id:crypto.randomUUID(),time:now,mode:'real',agent:'designer',text,type:job.status==='applied'?'info':'warning'});s.logs=s.logs.slice(0,300);const r=s.company.reports.find(r=>r.day===s.company.meetings.find(m=>m.id===job.meetingId)?.day);if(r){r.text+='\n'+text;r.sourceChanges??=[];r.sourceChanges.push({id:job.id,status:job.status,commit:job.commit,summary:job.summary});r.time=now;}return {ok:true};}
 throw Error('Acción de desarrollo inválida');
}
