const safeUrl=x=>{try{const u=new URL(x);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}};
import {eligible,id} from './core.js';
import {extractFundamentals,priceFeatures} from './fundamentals.js';
const headers={'User-Agent':'CesarHomeLab Research https://cesar-solla.pages.dev/','Accept':'application/json,application/rss+xml,application/atom+xml'};
const text=x=>String(x||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const field=(x,tag)=>text(x.match(new RegExp('<'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+tag+'>','i'))?.[1]);
export function parseFeed(xml){return [...String(xml).matchAll(/<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi)].slice(0,150).map(([,type,b])=>({title:field(b,'title'),summary:field(b,type==='entry'?'summary':'description'),url:type==='entry'?b.match(/<link[^>]*href=["']([^"']+)["']/i)?.[1]:field(b,'link'),publishedAt:Date.parse(field(b,type==='entry'?'updated':'pubDate')),cik:Number(field(b,'title').match(/\((\d{10})\)/)?.[1])||null})).filter(x=>x.title&&safeUrl(x.url)&&Number.isFinite(x.publishedAt));}
export function signalKind(item){const t=(item.title+' '+item.summary).toLowerCase();if(/item 1\.03|chapter 11|bankruptcy/.test(t))return {kind:'Estrés / insolvencia',strength:0,risk:true};if(/offering|private placement|dilution|item 3\.02|item 3\.01/.test(t))return {kind:'Financiación / cotización',strength:8,risk:true};if(/item 1\.01|awarded|contract|agreement|partnership/.test(t))return {kind:'Contrato / acuerdo',strength:28};if(/fda|pdufa|phase [123]|clinical|regulatory|approval/.test(t))return {kind:'Regulatorio / clínico',strength:28};if(/raises? (?:its )?(?:guidance|outlook)|guidance|forecast|outlook/.test(t))return {kind:'Previsiones / guidance',strength:27};if(/item 2\.02|earnings|financial results|quarter.*results/.test(t))return {kind:'Resultados / convocatoria',strength:20};if(/launch|new product|commercialization|acquisition|merger|buyback|repurchase/.test(t))return {kind:'Corporativo / lanzamiento',strength:24};if(/offering|private placement|dilution|item 3\.02|item 3\.01/.test(t))return {kind:'Financiación / cotización',strength:8,risk:true};return {kind:'Documento corporativo',strength:8};}
const stem=name=>name.replace(/(?:common|ordinary|capital) (?:stock|shares).*$/i,'').replace(/\b(incorporated|inc\.?|corporation|corp\.?|limited|ltd\.?|holdings?|company|co\.?)\b/gi,'').replace(/[^a-z0-9 ]/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();
export function matchIssuer(item,assets,ciks={}){if(item.cik)return assets.filter(a=>ciks[a.symbol]===item.cik);const body=text(item.title+' '+item.summary),explicit=[...body.matchAll(/\b(?:NASDAQ|NYSE|NYSE AMERICAN|AMEX)\s*[:\-]\s*([A-Z][A-Z0-9.\-]{0,7})\b/g)].map(m=>m[1]);if(explicit.length)return assets.filter(a=>explicit.includes(a.symbol));const title=item.title.toLowerCase();const matches=assets.filter(a=>{const n=stem(a.name);return n.length>=10&&title.includes(n);});return matches.length===1?matches:[];}
async function download(url,fetcher,json=true){const r=await fetcher(url,{headers,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Fuente HTTP '+r.status);if(Number(r.headers.get('content-length'))>20e6)throw Error('Respuesta demasiado grande');return json?r.json():r.text();}
export function rankCandidate(e,a,profile,policy={},now=Date.now(),peers={}){
 const m=profile?.fundamentals?.metrics||{},p=profile?.market||{};const reasons=[],warnings=[];let score=0;let blocked=false;
 const days=Number.isFinite(Date.parse(e.date))?(Date.parse(e.date)-now)/864e5:null;
 if(eligible(a)){blocked=true;warnings.push('Fuera del universo elegible');}
 if(e.signal){score+=e.signal.strength||0;reasons.push('Señal: '+e.signal.kind);if(e.signal.risk){score-=20;warnings.push('La noticia contiene una alerta; comprobar contexto');}if(e.signal.kind==='Estrés / insolvencia'){blocked=true;warnings.push('Señal explícita de insolvencia');}const age=(now-e.signal.publishedAt)/864e5;if(age<=1)score+=10;else if(age<=3)score+=5;else if(age>7)blocked=true;}
 else {score+=10;reasons.push('Calendario de resultados; aún no implica sorpresa positiva');}
 if(days!==null&&days>0&&days<=14){score+=15;reasons.push('Evento dentro de 14 días');}else if(days>14&&days<=30)score+=7;
 if(a.marketCap<=2e9)score+=4;
 const finance=/finance|financial|bank|insurance/i.test(a.sector||'');const fresh=m.annualAgeDays!==null&&m.annualAgeDays<=540;
 let available=0;if(fresh){if(Number.isFinite(m.netMargin)){available++;if(m.netMargin>0){score+=5;reasons.push('Beneficio anual positivo');}else warnings.push('Pérdidas anuales');}if(Number.isFinite(m.revenueYoY)){available++;if(m.revenueYoY>0){score+=6;reasons.push('Ingresos anuales en crecimiento');}else if(m.revenueYoY<-.15){score-=6;warnings.push('Ingresos caen más de 15%');}}
  if(!finance){if(Number.isFinite(m.fcf)){available++;if(m.fcf>0){score+=8;reasons.push('FCF anual positivo');}else {score-=4;warnings.push('FCF anual negativo');}}if(Number.isFinite(m.debtToEbitda)){available++;if(m.debtToEbitda<3){score+=5;reasons.push('Deuda/EBITDA aproximado menor de 3');}else if(m.debtToEbitda>6){score-=10;warnings.push('Apalancamiento elevado');}}}
  if(Number.isFinite(m.shareGrowth)){available++;if(m.shareGrowth>.3){score-=12;warnings.push('Dilución anual superior al 30%');}else if(m.shareGrowth<.05)score+=3;}
 }else warnings.push('Fundamentales anuales ausentes o antiguos');
 if(m.equityDate&&now-Date.parse(m.equityDate)<180*864e5&&Number.isFinite(m.equityLatest)&&m.equityLatest<=0){blocked=true;warnings.push('Patrimonio neto reciente no positivo');}
 if(Number.isFinite(p.averageDollarVolume)){available++;if(p.averageDollarVolume<1e6){blocked=true;warnings.push('Liquidez histórica inferior al mínimo');}else score+=4;}
 if(p.checkedAt&&now-p.checkedAt<2*864e5){if(p.relativeVolume>=1.5){score+=7;reasons.push('Volumen relativo elevado');}if((p.return21d<=-.15||p.return63d<=-.25)&&m.fcf>0){score+=5;reasons.push('Caída reciente con FCF positivo; comprobar motivo y splits');}if(p.return5d>.2){score-=8;warnings.push('Subida reciente: riesgo de catalizador ya descontado');}}
 for(const [key,direction] of [['pe',-1],['pb',-1],['evToEbitda',-1],['netMargin',1],['roe',1]]){const peer=peers[a.sector]?.[key];if(fresh&&peer?.n>=5&&m[key]>0){if((direction<0&&m[key]<peer.median)||(direction>0&&m[key]>peer.median)){score+=1;reasons.push(key+': favorable frente a muestra sectorial de '+peer.n);}}}
 if(available<3){score-=10;warnings.push('Cobertura financiera limitada; no se certifica salud');}
 score=Math.max(0,Math.min(100,Math.round(score)));const threshold=policy.minScore??45;
 const hasTrigger=!!e.signal||(days>0&&days<=14&&fresh&&((!finance&&m.fcf>0)||finance&&m.netMargin>0)&&m.revenueYoY>0);
 return {score,threshold,eligible:!blocked&&hasTrigger&&score>=threshold,blocked,reasons,warnings,coverage:available,scoredAt:now,policyVersion:policy.version||1,label:'Prioridad de investigación; no probabilidad de rentabilidad'};
}
export function sectorPeers(assets,profiles){const out={};for(const a of assets){const m=profiles[a.symbol]?.fundamentals?.metrics;if(!m||m.annualAgeDays>540)continue;for(const k of ['pe','pb','evToEbitda','netMargin','roe']){if(!(m[k]>0))continue;out[a.sector]??={};out[a.sector][k]??=[];out[a.sector][k].push(m[k]);}}for(const group of Object.values(out))for(const [k,values] of Object.entries(group)){values.sort((a,b)=>a-b);const i=Math.floor(values.length/2);group[k]={n:values.length,median:values.length%2?values[i]:(values[i-1]+values[i])/2};}return out;}
export async function discover(s,log,{fetcher=fetch,now=Date.now()}={}){
 const d=s.real;d.profiles??={};d.discovery??={sources:{},lastAt:0};const assets=d.assets.filter(a=>!eligible(a,s.config));
 if(!d.ciks||now-(d.cikAt||0)>7*864e5){try{const j=await download('https://www.sec.gov/files/company_tickers_exchange.json',fetcher);const fields=j.fields;const ti=fields.indexOf('ticker'),ci=fields.indexOf('cik');if(ti<0||ci<0)throw Error('Mapa SEC inválido');const wanted=new Set(assets.map(a=>a.symbol));d.ciks=Object.fromEntries(j.data.filter(r=>wanted.has(r[ti])).map(r=>[r[ti],Number(r[ci])]));d.cikAt=now;}catch(e){d.discovery.sources.mapping={at:now,error:e.message};}}
 const feeds=[['SEC 8-K','https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&count=100&output=atom'],['PR Newswire','https://www.prnewswire.com/rss/news-releases-list.rss']];let added=0;
 const feedResults=await Promise.allSettled(feeds.map(async([name,url])=>({name,url,items:parseFeed(await download(url,fetcher,false))})));
 for(let i=0;i<feedResults.length;i++){const r=feedResults[i];if(r.status==='rejected'){d.discovery.sources[feeds[i][0]]={at:now,error:String(r.reason.message).slice(0,150)};continue;}const {name,items}=r.value;let matched=0;for(const item of items){if(item.publishedAt>now+5*60e3||now-item.publishedAt>7*864e5)continue;for(const a of matchIssuer(item,assets,d.ciks)){matched++;const kind=signalKind(item),eventId=id(a.symbol,item.url);if(d.events.some(e=>e.id===eventId))continue;d.events.push({id:eventId,symbol:a.symbol,date:null,kind:kind.kind,title:item.title.slice(0,220),summary:'Señal detectada por código; fecha e impacto pendientes de investigar.',source:item.url,confirmed:false,estimated:true,status:'verificar',signal:{...kind,origin:name,url:item.url,headline:item.title.slice(0,220),excerpt:item.summary.slice(0,1600),publishedAt:item.publishedAt},createdAt:now,plan:null,reasons:['Señal de noticia/documento; no catalizador confirmado']});added++;}}d.discovery.sources[name]={at:now,items:items.length,matched,error:null};}
 const rough=d.events.filter(e=>!['abierto','descartado','caducado'].includes(e.status)&&(e.signal||Date.parse(e.date)>now)).map(e=>({e,a:assets.find(a=>a.symbol===e.symbol)})).filter(x=>x.a).sort((x,y)=>(y.e.signal?.strength||0)-(x.e.signal?.strength||0)||(Date.parse(x.e.date)||now+45*864e5)-(Date.parse(y.e.date)||now+45*864e5));
 const symbols=[...new Set(rough.map(x=>x.a.symbol))].filter(symbol=>!d.profiles[symbol]||now-(d.profiles[symbol].checkedAt||0)>6*3600e3).slice(0,4);
 let benchmark=d.benchmark;if(symbols.length&&(!benchmark||now-(d.benchmarkAt||0)>864e5)){try{benchmark=await download('https://query1.finance.yahoo.com/v8/finance/chart/SPY?interval=1d&range=1y&includePrePost=false',fetcher);d.benchmark=benchmark;d.benchmarkAt=now;}catch{/* Beta stays unavailable, not zero. */}}
 // Sequential SEC requests stay far below its 10 requests/second limit.
 for(const symbol of symbols){const a=assets.find(a=>a.symbol===symbol),old=d.profiles[symbol]||{},profile={...old,checkedAt:now,errors:[]};if(d.ciks?.[symbol]&&(!old.fundamentals||now-old.fundamentals.checkedAt>7*864e5)){try{const j=await download('https://data.sec.gov/api/xbrl/companyfacts/CIK'+String(d.ciks[symbol]).padStart(10,'0')+'.json',fetcher);if(Number(j.cik)!==d.ciks[symbol])throw Error('CIK no coincide');profile.fundamentals=extractFundamentals(j,a,now);}catch(e){profile.errors.push('SEC: '+e.message);}}else if(!d.ciks?.[symbol])profile.errors.push('CIK no localizado');
  try{const j=await download('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol.replaceAll('.','-'))+'?interval=1d&range=1y&includePrePost=false',fetcher);const meta=j.chart?.result?.[0]?.meta;if(meta?.symbol!==symbol.replaceAll('.','-')||meta?.currency!=='USD'||meta?.instrumentType!=='EQUITY')throw Error('Identidad de precios no válida');profile.market=priceFeatures(j,benchmark,now);}catch(e){profile.errors.push('Precios: '+e.message);}d.profiles[symbol]=profile;}
 d.peers=sectorPeers(assets,d.profiles);for(const {e,a} of rough)e.preScore=rankCandidate(e,a,d.profiles[a.symbol],s.policy,now,d.peers);
 d.profiles=Object.fromEntries(Object.entries(d.profiles).sort((a,b)=>b[1].checkedAt-a[1].checkedAt).slice(0,250));d.discovery.lastAt=now;d.discovery.universe=assets.length;d.discovery.enriched=Object.keys(d.profiles).length;d.discovery.queued=rough.filter(x=>x.e.preScore?.eligible).length;d.discovery.newSignals=added;
 if(added||symbols.length)log(s,'scout',`Radar por código: ${assets.length} empresas filtradas; ${added} señales nuevas, ${symbols.length} fichas enriquecidas y ${d.discovery.queued} candidatas priorizadas`);
}
